const expenses = [
  {
    description: 'Energia elétrica',
    amount: '150.55',
    type: 'saída',
    frequency: 'recorrente',
    date: '2020-01-10',
  },
  {
    description: 'Água',
    amount: '75.55',
    type: 'saída',
    frequency: 'recorrente',
    date: '2020-01-15',
  },
  {
    description: 'Telefone',
    amount: '99.99',
    type: 'saída',
    frequency: 'recorrente',
    date: '2020-01-23',
  },
  {
    description: 'Plano de Saúde',
    amount: '300.00',
    type: 'saída',
    frequency: 'recorrente',
    date: '2020-01-23',
  },
  {
    description: 'Compras do mês',
    amount: '625.78',
    type: 'saída',
    frequency: 'recorrente',
    date: '2020-01-23',
  },
  {
    description: 'Lanche',
    amount: '45.70',
    type: 'saída',
    frequency: 'eventual',
    date: '2020-01-23',
  },
  {
    description: 'Blusa Iron Man',
    amount: '150.00',
    type: 'saída',
    frequency: 'eventual',
    date: '2020-01-23',
  },
  {
    description: 'Blusa',
    amount: '95.70',
    type: 'saída',
    frequency: 'eventual',
    date: '2020-01-23',
  },
  {
    description: 'Energia elétrica',
    amount: '125.55',
    type: 'saída',
    frequency: 'recorrente',
    date: '2020-02-10',
  },
  {
    description: 'Água',
    amount: '90.15',
    type: 'saída',
    frequency: 'recorrente',
    date: '2020-02-15',
  },
  {
    description: 'Telefone',
    amount: '99.99',
    type: 'saída',
    frequency: 'recorrente',
    date: '2020-02-23',
  },
  {
    description: 'Plano de Saúde',
    amount: '300.00',
    type: 'saída',
    frequency: 'recorrente',
    date: '2020-02-23',
  },
  {
    description: 'Compras do mês',
    amount: '540.00',
    type: 'saída',
    frequency: 'recorrente',
    date: '2020-02-25',
  },
  {
    description: 'Parcela do Celular 1/5',
    amount: '150.99',
    type: 'saída',
    frequency: 'eventual',
    date: '2020-02-26',
  },
  {
    description: 'Cinema',
    amount: '45.00',
    type: 'saída',
    frequency: 'eventual',
    date: '2020-02-23',
  },
  {
    description: 'Energia elétrica',
    amount: '97.00',
    type: 'saída',
    frequency: 'recorrente',
    date: '2020-03-10',
  },
  {
    description: 'Água',
    amount: '100.10',
    type: 'saída',
    frequency: 'recorrente',
    date: '2020-03-15',
  },
  {
    description: 'Telefone',
    amount: '99.99',
    type: 'saída',
    frequency: 'recorrente',
    date: '2020-03-23',
  },
  {
    description: 'Plano de Saúde',
    amount: '300.00',
    type: 'saída',
    frequency: 'recorrente',
    date: '2020-03-23',
  },
  {
    description: 'Compras do mês',
    amount: '800.50',
    type: 'saída',
    frequency: 'recorrente',
    date: '2020-03-17',
  },
  {
    description: 'Parcela do Celular 2/5',
    amount: '150.99',
    type: 'saída',
    frequency: 'eventual',
    date: '2020-03-18',
  },
  {
    description: 'Troca de Oléo do carro',
    amount: '90.00',
    type: 'saída',
    frequency: 'eventual',
    date: '2020-03-23',
  },
  {
    description: 'Energia elétrica',
    amount: '75.99',
    type: 'saída',
    frequency: 'recorrente',
    date: '2020-04-10',
  },
  {
    description: 'Água',
    amount: '80.33',
    type: 'saída',
    frequency: 'recorrente',
    date: '2020-04-15',
  },
  {
    description: 'Telefone',
    amount: '99.99',
    type: 'saída',
    frequency: 'recorrente',
    date: '2020-04-23',
  },
  {
    description: 'Plano de Saúde',
    amount: '300.00',
    type: 'saída',
    frequency: 'recorrente',
    date: '2020-04-23',
  },
  {
    description: 'Compras do mês',
    amount: '600.00',
    type: 'saída',
    frequency: 'recorrente',
    date: '2020-04-25',
  },
  {
    description: 'Parcela do Celular 3/5',
    amount: '150.99',
    type: 'saída',
    frequency: 'eventual',
    date: '2020-04-26',
  },
  {
    description: 'Ebook de React Js',
    amount: '85.95',
    type: 'saída',
    frequency: 'eventual',
    date: '2020-04-13',
  },
  {
    description: 'Energia elétrica',
    amount: '125.55',
    type: 'saída',
    frequency: 'recorrente',
    date: '2020-05-10',
  },
  {
    description: 'Água',
    amount: '90.15',
    type: 'saída',
    frequency: 'recorrente',
    date: '2020-05-15',
  },
  {
    description: 'Telefone',
    amount: '99.99',
    type: 'saída',
    frequency: 'recorrente',
    date: '2020-05-23',
  },
  {
    description: 'Plano de Saúde',
    amount: '300.00',
    type: 'saída',
    frequency: 'recorrente',
    date: '2020-05-23',
  },
  {
    description: 'Compras do mês',
    amount: '540.00',
    type: 'saída',
    frequency: 'recorrente',
    date: '2020-05-25',
  },
  {
    description: 'Parcela do Celular 4/5',
    amount: '150.99',
    type: 'saída',
    frequency: 'eventual',
    date: '2020-05-26',
  },
  {
    description: 'Energia elétrica',
    amount: '200.00',
    type: 'saída',
    frequency: 'recorrente',
    date: '2020-06-10',
  },
  {
    description: 'Água',
    amount: '150.00',
    type: 'saída',
    frequency: 'recorrente',
    date: '2020-06-15',
  },
  {
    description: 'Telefone',
    amount: '99.99',
    type: 'saída',
    frequency: 'recorrente',
    date: '2020-06-23',
  },
  {
    description: 'Plano de Saúde',
    amount: '300.00',
    type: 'saída',
    frequency: 'recorrente',
    date: '2020-06-23',
  },
  {
    description: 'Compras do mês',
    amount: '559.15',
    type: 'saída',
    frequency: 'recorrente',
    date: '2020-06-25',
  },
  {
    description: 'Parcela do Celular 5/5',
    amount: '150.99',
    type: 'saída',
    frequency: 'eventual',
    date: '2020-06-26',
  },
  {
    description: 'Perfume',
    amount: '250.00',
    type: 'saída',
    frequency: 'eventual',
    date: '2020-06-21',
  },
  {
    description: 'Energia elétrica',
    amount: '200.00',
    type: 'saída',
    frequency: 'recorrente',
    date: '2020-07-10',
  },
  {
    description: 'Água',
    amount: '150.00',
    type: 'saída',
    frequency: 'recorrente',
    date: '2020-07-15',
  },
  {
    description: 'Telefone',
    amount: '99.99',
    type: 'saída',
    frequency: 'recorrente',
    date: '2020-07-23',
  },
  {
    description: 'Plano de Saúde',
    amount: '300.00',
    type: 'saída',
    frequency: 'recorrente',
    date: '2020-07-23',
  },
  {
    description: 'Compras do mês',
    amount: '559.15',
    type: 'saída',
    frequency: 'recorrente',
    date: '2020-07-25',
  },
  {
    description: 'Parcela do Celular 5/5',
    amount: '150.99',
    type: 'saída',
    frequency: 'eventual',
    date: '2020-07-26',
  },
  {
    description: 'Perfume',
    amount: '250.00',
    type: 'saída',
    frequency: 'eventual',
    date: '2020-07-21',
  },
  {
    description: 'Energia elétrica',
    amount: '200.00',
    type: 'saída',
    frequency: 'recorrente',
    date: '2020-08-10',
  },
  {
    description: 'Água',
    amount: '150.00',
    type: 'saída',
    frequency: 'recorrente',
    date: '2020-08-15',
  },
  {
    description: 'Telefone',
    amount: '99.99',
    type: 'saída',
    frequency: 'recorrente',
    date: '2020-08-23',
  },
  {
    description: 'Plano de Saúde',
    amount: '300.00',
    type: 'saída',
    frequency: 'recorrente',
    date: '2020-08-23',
  },
  {
    description: 'Compras do mês',
    amount: '559.15',
    type: 'saída',
    frequency: 'recorrente',
    date: '2020-08-25',
  },
  {
    description: 'Parcela do Celular 5/5',
    amount: '150.99',
    type: 'saída',
    frequency: 'eventual',
    date: '2020-08-26',
  },
  {
    description: 'Perfume',
    amount: '250.00',
    type: 'saída',
    frequency: 'eventual',
    date: '2020-08-21',
  },
  {
    description: 'Energia elétrica',
    amount: '200.00',
    type: 'saída',
    frequency: 'recorrente',
    date: '2020-09-10',
  },
  {
    description: 'Água',
    amount: '150.00',
    type: 'saída',
    frequency: 'recorrente',
    date: '2020-09-15',
  },
  {
    description: 'Telefone',
    amount: '99.99',
    type: 'saída',
    frequency: 'recorrente',
    date: '2020-09-23',
  },
  {
    description: 'Plano de Saúde',
    amount: '300.00',
    type: 'saída',
    frequency: 'recorrente',
    date: '2020-09-23',
  },
  {
    description: 'Compras do mês',
    amount: '559.15',
    type: 'saída',
    frequency: 'recorrente',
    date: '2020-09-25',
  },
  {
    description: 'Parcela do Celular 5/5',
    amount: '150.99',
    type: 'saída',
    frequency: 'eventual',
    date: '2020-09-26',
  },
  {
    description: 'Perfume',
    amount: '250.00',
    type: 'saída',
    frequency: 'eventual',
    date: '2020-09-21',
  },
  {
    description: 'Energia elétrica',
    amount: '250.00',
    type: 'saída',
    frequency: 'recorrente',
    date: '2020-10-10',
  },
  {
    description: 'Água',
    amount: '90.00',
    type: 'saída',
    frequency: 'recorrente',
    date: '2020-10-15',
  },
  {
    description: 'Telefone',
    amount: '99.99',
    type: 'saída',
    frequency: 'recorrente',
    date: '2020-10-23',
  },
  {
    description: 'Plano de Saúde',
    amount: '350.00',
    type: 'saída',
    frequency: 'recorrente',
    date: '2020-10-23',
  },
  {
    description: 'Compras do mês',
    amount: '702.00',
    type: 'saída',
    frequency: 'recorrente',
    date: '2020-10-25',
  },
  {
    description: 'Cafeteira',
    amount: '253.00',
    type: 'saída',
    frequency: 'eventual',
    date: '2020-10-26',
  },
  {
    description: 'Pizza',
    amount: '90.00',
    type: 'saída',
    frequency: 'eventual',
    date: '2020-10-19',
  },
  {
    description: 'Energia elétrica',
    amount: '240.00',
    type: 'saída',
    frequency: 'recorrente',
    date: '2020-11-11',
  },
  {
    description: 'Água',
    amount: '95.30',
    type: 'saída',
    frequency: 'recorrente',
    date: '2020-11-16',
  },
  {
    description: 'Telefone',
    amount: '92.90',
    type: 'saída',
    frequency: 'recorrente',
    date: '2020-11-25',
  },
  {
    description: 'Plano de Saúde',
    amount: '330.00',
    type: 'saída',
    frequency: 'recorrente',
    date: '2020-11-24',
  },
  {
    description: 'Compras do mês',
    amount: '998.00',
    type: 'saída',
    frequency: 'recorrente',
    date: '2020-11-26',
  },
  {
    description: 'Cafeteira',
    amount: '253.00',
    type: 'saída',
    frequency: 'eventual',
    date: '2020-11-22',
  },
  {
    description: 'Pizza',
    amount: '92.00',
    type: 'saída',
    frequency: 'eventual',
    date: '2020-11-12',
  },
  ,
]

export default expenses
